repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.13.3
    hooks:
      - id: commitlint

  - repo: local
    hooks:
      - id: kingfisher
        name: kingfisher scan
        description: detect secrets in your data.
        entry: kingfisher scan --exclude public --exclude static --exclude dist --exclude src/img --no-update-check
        language: system
        stages: ["pre-commit", "pre-push"]
